-- ==================================================================
-- PHẦN 1: RAW DATA LAYER (Lớp Đồng)
-- Dùng để lưu JSON thô từ Riot API, tránh mất dữ liệu
-- ==================================================================

CREATE TABLE IF NOT EXISTS raw_matches (
    match_id TEXT PRIMARY KEY,           -- ID trận đấu (VD: VN2_123456)
    data JSONB NOT NULL,                 -- Toàn bộ cục JSON response
    region TEXT,                         -- VD: VN2, NA1
    is_processed BOOLEAN DEFAULT false,  -- Cờ đánh dấu đã chạy Edge Function chưa
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Index GIN để query nhanh bên trong JSON nếu cần debug
CREATE INDEX IF NOT EXISTS idx_gin_raw_matches_data ON raw_matches USING GIN (data);


-- ==================================================================
-- PHẦN 2: MASTER DATA (Thông tin định danh & Xếp hạng hiện tại)
-- ==================================================================

-- Bảng Players: Lưu thông tin định danh và Rank HIỆN TẠI (từ endpoint League-V4)
CREATE TABLE IF NOT EXISTS players (
    puuid TEXT PRIMARY KEY,
    game_name TEXT, 
    tag_line TEXT,
    
    -- Thông tin Rank hiện tại (Snapshot)
    tier TEXT,                           -- VD: DIAMOND
    rank TEXT,                           -- VD: I, II
    league_points INTEGER DEFAULT 0,
    wins INTEGER DEFAULT 0,
    losses INTEGER DEFAULT 0,
    
    -- Cờ trạng thái
    veteran BOOLEAN DEFAULT false,
    inactive BOOLEAN DEFAULT false,
    fresh_blood BOOLEAN DEFAULT false,
    hot_streak BOOLEAN DEFAULT false,
    
    updated_at TIMESTAMPTZ DEFAULT now() -- Thời điểm cập nhật rank gần nhất
);

-- Index hỗ trợ tìm kiếm người chơi nhanh
CREATE INDEX IF NOT EXISTS idx_players_identity ON players (game_name, tag_line);
CREATE INDEX IF NOT EXISTS idx_players_leaderboard ON players (tier, league_points DESC);


-- Bảng Matches: Lưu thông tin chung của trận đấu (Sau khi parse)
CREATE TABLE IF NOT EXISTS matches (
    match_id TEXT PRIMARY KEY,
    data_version TEXT,                   -- Phiên bản data
    game_version TEXT,                   -- Phiên bản game (VD: Version 14.22...)
    game_datetime TIMESTAMPTZ,           -- Thời gian diễn ra trận
    game_length FLOAT,                   -- Thời lượng (giây)
    queue_id INTEGER,                    -- Loại hàng chờ (Rank, Normal)
    tft_set_number INTEGER,              -- Mùa (VD: Set 10, Set 11)
    created_at TIMESTAMPTZ DEFAULT now()
);


-- ==================================================================
-- PHẦN 3: ANALYTICAL DATA (Lớp Bạc - Đã chuẩn hóa 3NF)
-- ==================================================================

-- Bảng Participants: Thay thế cho 'players_matches_link'
-- Lưu kết quả của 1 người chơi trong 1 trận đấu
CREATE TABLE IF NOT EXISTS participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Khóa chính tự tăng
    match_id TEXT REFERENCES matches(match_id) ON DELETE CASCADE,
    puuid TEXT REFERENCES players(puuid) ON DELETE SET NULL, -- Nếu xóa player, giữ lại lịch sử nhưng set NULL
    
    -- Chỉ số quan trọng
    placement INTEGER NOT NULL,          -- Hạng (1-8)
    level INTEGER NOT NULL,              -- Level cuối trận
    gold_left INTEGER,                   -- Vàng còn dư
    last_round INTEGER,                  -- Round cuối cùng sống sót
    time_eliminated FLOAT,               -- Thời gian bị loại
    total_damage_to_players INTEGER,
    
    -- Constraint: 1 người chỉ tham gia 1 trận 1 lần
    UNIQUE(match_id, puuid)
);

CREATE INDEX IF NOT EXISTS idx_participants_puuid ON participants(puuid);
CREATE INDEX IF NOT EXISTS idx_participants_placement ON participants(placement);


-- Bảng Units: Các tướng trên bàn cờ của người chơi (Đã tách khỏi JSON)
CREATE TABLE IF NOT EXISTS match_units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Unit Instance ID
    participant_id BIGINT REFERENCES participants(id) ON DELETE CASCADE, -- Thuộc về participant nào
    
    character_id TEXT NOT NULL,          -- ID Tướng (VD: TFT9_Garen)
    tier INTEGER DEFAULT 1,              -- Số sao (1, 2, 3)
    item_names TEXT[],                   -- (Tùy chọn) Có thể lưu mảng tên item ở đây để query nhanh (Phi chuẩn hóa nhẹ)
    name TEXT,                           -- Tên hiển thị (nếu cần)
    rarity INTEGER                       -- Độ hiếm (vàng)
);

-- Index để thống kê: "Tướng nào được chơi nhiều nhất?"
CREATE INDEX IF NOT EXISTS idx_units_character ON match_units(character_id);


-- Bảng Unit Items: Tách items ra bảng riêng (Chuẩn hóa triệt để 1NF)
-- Dùng bảng này nếu bạn muốn thống kê chi tiết: "Garen thường cầm đồ gì?"
CREATE TABLE IF NOT EXISTS match_unit_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_instance_id BIGINT REFERENCES match_units(id) ON DELETE CASCADE,
    item_name TEXT NOT NULL              -- Tên trang bị (VD: Sunfire Cape)
);

CREATE INDEX IF NOT EXISTS idx_items_name ON match_unit_items(item_name);

-- ==================================================================
-- PHẦN 4: TRAITS (Tộc/Hệ - Optional)
-- ==================================================================
-- Lưu thông tin kích hoạt tộc hệ của người chơi trong trận
CREATE TABLE IF NOT EXISTS match_traits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_id BIGINT REFERENCES participants(id) ON DELETE CASCADE,
    name TEXT NOT NULL,                  -- Tên tộc hệ (VD: Demacia)
    num_units INTEGER,                   -- Số tướng thuộc tộc này trên sân
    tier_current INTEGER,                -- Mốc kích hoạt hiện tại (VD: Mốc 2)
    tier_total INTEGER                   -- Mốc tối đa
);